package com.example.kafka_test.pojo;

import java.util.Date;

public class LineVideoConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.line_classify_level1_id
     *
     * @mbggenerated
     */
    private Integer lineClassifyLevel1Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.line_classify_level2_id
     *
     * @mbggenerated
     */
    private Integer lineClassifyLevel2Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.line_classify_level3_id
     *
     * @mbggenerated
     */
    private Integer lineClassifyLevel3Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.line_classify_level4_id
     *
     * @mbggenerated
     */
    private Integer lineClassifyLevel4Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.video_url
     *
     * @mbggenerated
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.place
     *
     * @mbggenerated
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.del
     *
     * @mbggenerated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.create_source
     *
     * @mbggenerated
     */
    private String createSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_video_config.update_source
     *
     * @mbggenerated
     */
    private String updateSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.id
     *
     * @return the value of line_video_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.id
     *
     * @param id the value for line_video_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.line_classify_level1_id
     *
     * @return the value of line_video_config.line_classify_level1_id
     *
     * @mbggenerated
     */
    public Integer getLineClassifyLevel1Id() {
        return lineClassifyLevel1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.line_classify_level1_id
     *
     * @param lineClassifyLevel1Id the value for line_video_config.line_classify_level1_id
     *
     * @mbggenerated
     */
    public void setLineClassifyLevel1Id(Integer lineClassifyLevel1Id) {
        this.lineClassifyLevel1Id = lineClassifyLevel1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.line_classify_level2_id
     *
     * @return the value of line_video_config.line_classify_level2_id
     *
     * @mbggenerated
     */
    public Integer getLineClassifyLevel2Id() {
        return lineClassifyLevel2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.line_classify_level2_id
     *
     * @param lineClassifyLevel2Id the value for line_video_config.line_classify_level2_id
     *
     * @mbggenerated
     */
    public void setLineClassifyLevel2Id(Integer lineClassifyLevel2Id) {
        this.lineClassifyLevel2Id = lineClassifyLevel2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.line_classify_level3_id
     *
     * @return the value of line_video_config.line_classify_level3_id
     *
     * @mbggenerated
     */
    public Integer getLineClassifyLevel3Id() {
        return lineClassifyLevel3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.line_classify_level3_id
     *
     * @param lineClassifyLevel3Id the value for line_video_config.line_classify_level3_id
     *
     * @mbggenerated
     */
    public void setLineClassifyLevel3Id(Integer lineClassifyLevel3Id) {
        this.lineClassifyLevel3Id = lineClassifyLevel3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.line_classify_level4_id
     *
     * @return the value of line_video_config.line_classify_level4_id
     *
     * @mbggenerated
     */
    public Integer getLineClassifyLevel4Id() {
        return lineClassifyLevel4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.line_classify_level4_id
     *
     * @param lineClassifyLevel4Id the value for line_video_config.line_classify_level4_id
     *
     * @mbggenerated
     */
    public void setLineClassifyLevel4Id(Integer lineClassifyLevel4Id) {
        this.lineClassifyLevel4Id = lineClassifyLevel4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.video_url
     *
     * @return the value of line_video_config.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.video_url
     *
     * @param videoUrl the value for line_video_config.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.place
     *
     * @return the value of line_video_config.place
     *
     * @mbggenerated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.place
     *
     * @param place the value for line_video_config.place
     *
     * @mbggenerated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.del
     *
     * @return the value of line_video_config.del
     *
     * @mbggenerated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.del
     *
     * @param del the value for line_video_config.del
     *
     * @mbggenerated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.create_time
     *
     * @return the value of line_video_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.create_time
     *
     * @param createTime the value for line_video_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.update_time
     *
     * @return the value of line_video_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.update_time
     *
     * @param updateTime the value for line_video_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.create_source
     *
     * @return the value of line_video_config.create_source
     *
     * @mbggenerated
     */
    public String getCreateSource() {
        return createSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.create_source
     *
     * @param createSource the value for line_video_config.create_source
     *
     * @mbggenerated
     */
    public void setCreateSource(String createSource) {
        this.createSource = createSource == null ? null : createSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_video_config.update_source
     *
     * @return the value of line_video_config.update_source
     *
     * @mbggenerated
     */
    public String getUpdateSource() {
        return updateSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_video_config.update_source
     *
     * @param updateSource the value for line_video_config.update_source
     *
     * @mbggenerated
     */
    public void setUpdateSource(String updateSource) {
        this.updateSource = updateSource == null ? null : updateSource.trim();
    }
}