package com.example.kafka_test.dao;

import com.example.kafka_test.pojo.LineVideoConfig;

public interface LineVideoConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int insert(LineVideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int insertSelective(LineVideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    LineVideoConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineVideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LineVideoConfig record);
}