package com.example.kafka_test.dao;


import com.example.kafka_test.dto.video.LineVideoConfigInsertDto;
import com.example.kafka_test.pojo.LineClassify;
import com.example.kafka_test.pojo.LineVideoConfig;
import com.example.kafka_test.pojo.query.LineClassifyQuery;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface LineVideoConfigDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int insert(LineVideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int insertSelective(LineVideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    LineVideoConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineVideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_video_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LineVideoConfig record);
}
